apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: python-app
  namespace: default
  labels:
    app.kubernetes.io/name: python-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: python-app
