apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nodejs-api
  namespace: default
  labels:
    app.kubernetes.io/name: nodejs-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nodejs-api
