apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: springboot-app
  namespace: default
  labels:
    app.kubernetes.io/name: springboot-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: springboot-app
